version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /var/www
    volumes:
      - .:/var/www
    links:
      - mysql
    image: php-practice
  mysql:
    image: mysql:8.0
    command: mysqld --sql_mode=""
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3306
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    restart: always
    ports:
      - "8080:80"